import type {Metadata} from "next";
import "../styles/fontiran.css";
import "../styles/globals.css";
import StoreProvider from "@/lib/redux/StoreProvider";
import ChakraProviderConfig from "@/lib/chakra/ChakraProviderConfig";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <StoreProvider>
            <ChakraProviderConfig>{children}</ChakraProviderConfig>
        </StoreProvider>
        </body>
        </html>
    );
}
