export const color = {
    primary: {
        lighter: "primary.lighter",
        light: "primary.light",
        main: "primary.main",
        dark: "primary.dark",
        darker: "primary.darker",
    },
    secondary: {
        lighter: "secondary.lighter",
        light: "secondary.light",
        main: "secondary.main",
        dark: "secondary.dark",
        darker: "secondary.darker",
    },
    info: {
        lighter: "info.lighter",
        light: "info.light",
        main: "info.main",
        dark: "info.dark",
        darker: "info.darker",
    },
    success: {
        lighter: "success.lighter",
        light: "success.light",
        main: "success.main",
        dark: "success.dark",
        darker: "success.darker",
    },
    warning: {
        lighter: "warning.lighter",
        light: "warning.light",
        main: "warning.main",
        dark: "warning.dark",
        darker: "warning.darker",
    },
    error: {
        lighter: "error.lighter",
        light: "error.light",
        main: "error.main",
        dark: "error.dark",
        darker: "error.darker",
    },
    grey: {
        _0: "grey._0",
        _100: "grey._100",
        _200: "grey._200",
        _300: "grey._300",
        _400: "grey._400",
        _500: "grey._500",
        _600: "grey._600",
        _700: "grey._700",
        _800: "grey._800",
        _900: "grey._900",
        _1000: "grey._1000",
    },
    text: {
        primary: "text.primary",
        secondary: "text.secondary",
        disabled: "text.disabled",
        reverse: "text.reverse",
        button: "text.button",
    },
    icon: {
        primary: "icon.primary",
        secondary: "icon.secondary",
        disabled: "icon.disabled",
        colorPrimary: "icon.colorPrimary",
        colorSecondary: "icon.colorSecondary",
        colorWarning: "icon.colorWarning",
        colorInfo: "icon.colorInfo",
        colorSuccess: "icon.colorSuccess",
        colorError: "icon.colorError",
        reverse: "icon.reverse",
    },
    base: {
        background: "base.background",
        menu: "base.menu",
        side: "base.side",
        card: "base.card",
        textField: "base.textField",
        textFieldDisabled: "base.textFieldDisabled",
        textFieldStroke: "base.textFieldStroke",
    },
};
export default color